version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - DEBUG=1
    env_file:
      - .env
    volumes:
      - ./:/app
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 80 --reload

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      #- ./db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      #- ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    #command: sh -c "echo 'host all all all md5' >> /var/lib/postgresql/data/pg_hba.conf && docker-entrypoint.sh postgres"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
