name: Deploy
run-name: Deploy on server initiated by ${{ github.actor }}
on:
  [ push, pull_request ]
jobs:
    build-bundle-and-upload:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
            -   name: Setup ssh
                run: |
                    mkdir -p ~/.ssh/
                    echo "${{ secrets.SSH_KEY }}" > ~/.ssh/key
                    chmod 600 ~/.ssh/key
                    cat >> ~/.ssh/config <<END
                    Host n1.13dagger.com
                        User me
                        IdentityFile ~/.ssh/key
                        StrictHostKeyChecking=no
                    END
            -   name: git pull
                run: ssh n1.13dagger.com 'cd ${{ vars.DEPLOY_DIR }}; git pull'
            -   name: build
                run: ssh n1.13dagger.com 'cd ${{ vars.DEPLOY_DIR }}; docker-compose -f docker-compose-prod.yml build'
            -   name: compose restart
                run: ssh n1.13dagger.com 'cd ${{ vars.DEPLOY_DIR }}; docker-compose -f docker-compose-prod.yml down; docker-compose -f docker-compose-prod.yml up -d'
            -   name: run migrations
                run: ssh n1.13dagger.com 'cd ${{ vars.DEPLOY_DIR }}; docker-compose -f docker-compose-prod.yml run app poetry run alembic upgrade head'
